/**
 * ISS-1107: the authoritative classification of CLI routes in register.ts.
 *
 * A board write route calls its handler inside one of `CLI_REPORTING_RUNNERS`,
 * each of which reports the git state of the files written and honours
 * `--commit`. Every other handler is named here with a reason. A test parses
 * register.ts and fails on any handler call that is in neither place, so a new
 * route cannot skip the report by accident.
 */

/** Runners that report board writes (`runBoardWrite` directly, or a runner built on it). */
export const CLI_REPORTING_RUNNERS: readonly string[] = [
  "runBoardWrite",
  "runDeleteCommand",
  "runCheckpointCommand",
  "runCatalogWrite",
  "runRulingWrite",
  "runArrangementMaintenance",
];

/** Handlers that are not board writes, each with the reason. */
export const CLI_NON_BOARD_HANDLERS: Readonly<Record<string, string>> = {
  handleArrangementGet: "read",
  handleArrangementList: "read",
  handleBrief: "read",
  handleCapabilityCheck: "read",
  handleCapabilityGet: "read",
  handleCapabilityList: "read",
  handleCapabilityMatch: "read",
  handleCheckpointList: "read",
  handleConflictsList: "read",
  handleConflictsShow: "read",
  handleDispatch: "read",
  handleDispatchRecommend: "read",
  handleEarmarkGet: "read",
  handleExport: "read",
  handleFeedbackList: "read",
  handleGateAckGet: "read",
  handleGateAckList: "read",
  handleHandoverGet: "read",
  handleHandoverLatest: "read",
  handleHandoverTemplate: "read",
  handleHealth: "read",
  handleHookStatus: "read",
  handleIssueGet: "read",
  handleIssueList: "read",
  handleIssueMetaGet: "read",
  handleLandings: "read",
  handleLessonDigest: "read",
  handleLessonGet: "read",
  handleLessonList: "read",
  handleNoteGet: "read",
  handleNoteList: "read",
  handlePhaseTickets: "read",
  handleRecommend: "read",
  handleReference: "read",
  handleRepair: "read",
  handleReviewStats: "read",
  handleRosterList: "read",
  handleRulingGet: "read",
  handleRulingList: "read",
  handleSessionHealth: "read",
  handleSessionList: "read",
  handleSessionShow: "read",
  handleSessionWatch: "read",
  handleStatus: "read",
  handleTeamConfigShow: "read",
  handleTeamDoctor: "read",
  handleTermCheck: "read",
  handleTermGet: "read",
  handleTermList: "read",
  handleTermMatch: "read",
  handleTicketGet: "read",
  handleTicketList: "read",
  handleTicketMetaGet: "read",
  handleTicketNext: "read",
  handleBusToolHook: "Bus hook delivery: bus mailbox state, not a board item",
  handleCodexReview: "runs an external review; writes no board item",
  handleDuetSpawn: "spawns a worker session; writes spawn/ state (gitignored)",
  handleFeedbackCreate: "files product feedback outside the project",
  handleFeedbackOpen: "opens a feedback page",
  handleFeedbackVote: "votes on product feedback outside the project",
  handleGc: "admin: removes tombstones in bulk (CLI-only destructive workflow)",
  handleMergeDriver: "git merge driver invoked by git itself",
  handleMigrate: "admin: bulk migration of the whole ledger",
  handleReconcile: "admin: bulk duplicate-id reconciliation",
  handleReserve: "reserves display ids through remote git refs, no board file",
  handleResolve: "admin: settles merge conflicts the merge driver recorded",
  handleRosterWrite: "seat roster record on the presence plane, not a board item",
  handleSelftest: "integration smoke test: creates and deletes throwaway entities",
  handleSessionClearCompact: "autonomous session state (gitignored sessions/)",
  handleSessionCompactPrepare: "autonomous session state (gitignored sessions/)",
  handleSessionDelete: "autonomous session state (gitignored sessions/)",
  handleSessionIntel: "session intelligence state (gitignored telemetry)",
  handleSessionIntelPrompt: "session intelligence state (gitignored telemetry)",
  handleSessionIntelStart: "session intelligence state (gitignored telemetry)",
  handleSessionLimitStop: "autonomous session state (gitignored sessions/)",
  handleSessionMilestone: "autonomous session state (gitignored sessions/)",
  handleSessionRepair: "autonomous session state (gitignored sessions/)",
  handleSessionResumePrompt: "autonomous session state (gitignored sessions/)",
  handleSessionStop: "autonomous session state (gitignored sessions/)",
  handleSetup: "installs client integration outside the project",
  handleSetupSkill: "installs the skill outside the project",
  handleTeamConfigSet: "admin: team-mode configuration (CLI-only team workflow)",
  handleTeamInit: "admin: team-mode enablement (CLI-only team workflow)",
  handleTeamSetup: "admin: merge-driver installation (CLI-only team workflow)",
  handleUpdate: "updates the CLI itself",
};
